### ISSUE TITLE
Unit tests do not pass on master

### ISSUE THREAD

**Issue by AHumanFromCA** [zowe/vscode-extension-for-zowe#10]
The following tests fail on master:

```
 ● Extension Unit Tests › Testing that saveFile is executed successfully

    expect(received).toBe(expected) // Object.is equality

    Expected value to be:
      3
    Received:
      0

      703 |         expect(dataSetList.mock.calls[0][0]).toEqual(session);
      704 |         expect(dataSetList.mock.calls[0][1]).toBe("testFile");
    > 705 |         expect(pathToDataSet.mock.calls.length).toBe(3);
      706 |         expect(pathToDataSet.mock.calls[0][0]).toEqual(session);
      707 |         expect(pathToDataSet.mock.calls[0][1]).toBe(testDoc.fileName);
      708 |         expect(pathToDataSet.mock.calls[0][2]).toBe("testFile");

      at Object.<anonymous> (__tests__/extension.test.ts:705:49)
      at fulfilled (__tests__/extension.test.ts:28:17)

  ● Extension Unit Tests › Testing that safeSave is executed successfully

    expect(received).toEqual(expected)

    Expected value to equal:
      [Error]
    Received:
      ""

    Difference:

      Comparing two different types of values. Expected object but received string.

      894 |
      895 |         expect(showErrorMessage.mock.calls.length).toBe(1);
    > 896 |         expect(showErrorMessage.mock.calls[0][0]).toEqual(Error(""));
      897 |
      898 |         openTextDocument.mockResolvedValueOnce("test");
      899 |         openTextDocument.mockResolvedValueOnce("test");

      at Object.<anonymous> (__tests__/extension.test.ts:896:51)
      at fulfilled (__tests__/extension.test.ts:28:17)
```

**Comment by tjohnsonBCM** [comment]
Tests are passing on master branch now
