### ISSUE TITLE
Unable to use extension with secure credential plugin

### ISSUE THREAD

**Issue by ChrisBoehmCA** [zowe/vscode-extension-for-zowe#157]
A user is trying to use the Zowe VS Code extension with the secure credential plugin and it is not working. I tried to see if I could help but I'm stumped. He can issue `zowe files ls ds hlq` successfully, but VSCode says he has no default profile because the getDefaultProfile.js script fails. 

If he does `node getDefaultProfile.js` from the extension folder, he gets a message about a bad plugin as in the log below. I don't see anything about failing to require keytar, and it works from the command line...so not sure what is going on. 

Here is his imperative log

```
[2019/07/16 15:38:14.390] [DEBUG] [CliProfileManager.js:193] Loading secured field with key user for profile ("ca32" of type "zosmf").
[2019/07/16 15:38:14.391] [ERROR] [CliProfileManager.js:199] Unable to load secure field "user" associated with profile "ca32" of type "zosmf".
[2019/07/16 15:38:14.392] [ERROR] [CliProfileManager.js:203] Error: An invalid credential manager was passed in to the factory function!
A bad object was provided to the CredentialManagerFactory.initialize() method. This could be due to a bad plugin.
[2019/07/16 15:38:14.392] [ERROR] [CliProfileManager.js:205] Cause errors: { Error: A bad object was provided to the CredentialManagerFactory.initialize() method. This could be due to a bad plugin.
    at Function.<anonymous> (C:\Users\xxx\.vscode\extensions\zowe.vscode-extension-for-zowe-0.23.0\node_modules\@brightside\imperative\lib\security\src\CredentialManagerFactory.js:126:27)
    at Generator.next (<anonymous>)
    at C:\Users\xxx\.vscode\extensions\zowe.vscode-extension-for-zowe-0.23.0\node_modules\@brightside\imperative\lib\security\src\CredentialManagerFactory.js:17:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\xxxx\.vscode\extensions\zowe.vscode-extension-for-zowe-0.23.0\node_modules\@brightside\imperative\lib\security\src\CredentialManagerFactory.js:13:12)
    at Function.initialize (C:\Users\xxx\.vscode\extensions\zowe.vscode-extension-for-zowe-0.23.0\node_modules\@brightside\imperative\lib\security\src\CredentialManagerFactory.js:87:16)
    at Function.<anonymous> (C:\Users\xxx\.vscode\extensions\zowe.vscode-extension-for-zowe-0.23.0\node_modules\@brightside\imperative\lib\imperative\src\OverridesLoader.js:68:59)
    at Generator.next (<anonymous>)
    at C:\Users\xxxxx\.vscode\extensions\zowe.vscode-extension-for-zowe-0.23.0\node_modules\@brightside\imperative\lib\imperative\src\OverridesLoader.js:17:71
    at new Promise (<anonymous>)
  mDetails:
   { msg:
      'A bad object was provided to the CredentialManagerFactory.initialize() method. This could be due to a bad plugin.' },
  mMessage:
   'A bad object was provided to the CredentialManagerFactory.initialize() method. This could be due to a bad plugin.' }
[2019/07/16 15:38:14.393] [ERROR] [AbstractProfileManager.js:370] Load implementation error: Unable to load the secure field "user" associated with the profile "ca32" of type "zosmf".
```

**Comment by Colin-Stone** [comment]
Hi @ChrisBoehmCA So the customer is using Zowe cli without any issues and has the secure credentials plugin installed also?. Do we know what version?. 
As you know VSCode pulls it's own version of the node modules in so they are running as part of the VSCode node environment. I'm wondering if there is a weird namespace type of issue going on where we have the standalone version of CLI and the profiles all set up for secure credentials whilst VSCode implementation isn't set up for Secure Credentials. Does that sound plausible?.

**Comment by ChrisBoehmCA** [comment]
Ohhh actually I think I know the problem. He is probably using the `@latest` version of the CLI and the zowe extension needs lts-incremental

**Comment by Colin-Stone** [comment]
So he has an old version?. I would still like to be able to visualize however how the VSCode implementation can access the secure credentials pluginif it is installed in another node application

**Comment by ChrisBoehmCA** [comment]
Actually the new version. Lts incremental has the `@brightside` imports whereas `@latest` has the `@zowe` imports. So when the extension tries to load his secure credential plugin, it fails to find `@zowe/imperative`. 

The user's profiles are loaded via `getDefaultProfile.js` or `getAllProfiles.js`. These scripts do similar actions to the main program of Zowe CLI, calling Imperative.init to load all plugins the user has installed.   This initializes any secure credential plugin so that the profiles can be loaded.

**Comment by Colin-Stone** [comment]
Okay that makes sense.

**Comment by ChrisBoehmCA** [comment]
Fixed
