### ISSUE TITLE
VSCE Gituhub yml fails token

### ISSUE THREAD

**Issue by VidarDev** [zowe/vscode-extension-for-zowe#1682]
```Run npm run deploy
  npm run deploy
  shell: /usr/bin/bash -e {0}
  env:
    VSCE_PAT: ***

> vidar-design@0.0.[2](https://github.com/VidarDev/VSC-Theme/runs/5375794243?check_suite_focus=true#step:5:2) deploy /home/runner/work/VSC-Theme/VSC-Theme
> vsce publish --yarn

/home/runner/work/VSC-Theme/VSC-Theme/node_modules/vsce/out/package.js:1[3](https://github.com/VidarDev/VSC-Theme/runs/5375794243?check_suite_focus=true#step:5:3)6
    return (translations ?? [])
                          ^

SyntaxError: Unexpected token ?
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/runner/work/VSC-Theme/VSC-Theme/node_modules/vsce/out/main.js:27:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vidar-design@0.0.2 deploy: `vsce publish --yarn`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vidar-design@0.0.2 deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2022-03-01T13_20_09_[4](https://github.com/VidarDev/VSC-Theme/runs/5375794243?check_suite_focus=true#step:5:4)[17](https://github.com/VidarDev/VSC-Theme/runs/5375794243?check_suite_focus=true#step:5:17)Z-debug.log
Error: Process completed with exit code 1.```






Win 11 
Node 16.14.0
VSCODE 1.64

My token is right and is for all accessible

**Comment by zFernand0** [comment]
hey @VidarDev,
Could you provide more details about what you were trying to achieve?
It seems that you were trying to publish the extension (`vsce publish --yarn`)

**Comment by VidarDev** [comment]
i have fix it. the npm Version was take to 10.x have edit it to 16.x now it's work

**Comment by zFernand0** [comment]
Glad you got it to work.
I'm still curious to know if you were trying to publish the Zowe Explorer extension :yum:
Closing the issue for now.
