### ISSUE TITLE
Zowe CLI V2 - Profile IO Error: A Zowe V1 profile operation was attempted with a Zowe V2 configuration in use.

### ISSUE THREAD

**Issue by FALLAI-Denis** [zowe/vscode-extension-for-zowe#1820]
**Describe the bug**

See issue [#245](https://github.com/IBM/zopeneditor-about/issues/245)  on IBM / zopeneditor-about.

**Comment by zFernand0** [comment]
Thank you for opening the issue.

I'm afraid I'm having a hard time understanding what were the series of steps that caused this issue to occur in Zowe Explorer.

It seems that zOE freezes (or takes too long to initialize). Do you believe this is because of Zowe Explorer ?

Also, it seems that you were trying to use a `zowe profiles` command on the CLI v2 ?
```
For information, same message error on deprecated zowe cli command:

> zowe profiles set zosmf gmvs
Error occurred while setting default profile for zosmf.
Profile IO Error: A Zowe V1 profile operation was attempted with a Zowe V2 configuration in use.
```

---

I have seen this issue while testing different combinations, and it only seems to happen right after creating my first v2 profile and doing an `extRefresh` (or a > Zowe Explorer: Refresh Zowe Explorer` command in the command palette.
As a workaround, you can either do a full `> Developer: Reload Window` or close VSCode and reopen it.

---

Next time, please try to fill out the template. 
Thanks.

**Comment by JillieBeanSim** [comment]
Considering a refactor of ProfilesCache() to remove all calls to the CliProfileManager (old v1 method) to ProfileInfo (new v2 method) in next PI.  This refactor may remove these occurrences of the error shown.

**Comment by FALLAI-Denis** [comment]
Hi, 

Still same problem with Zowe Explorer 2.0.3.

The issue is triggered when calling the "Run IBM User Build" function in IBM Z Open Editor extension.
This function tries to validate first a "z/OSMF" profile, then a "ssh" profile. It blocks on the validation of the "z/OSMF" profile which does not respond.

```
[2022/06/09 18:54:23.206] [DEBUG] [extension.js:32] Initialized logger from VSCode extension
[2022/06/09 18:54:24.164] [DEBUG] [extension.js:32] Zowe Explorer is using the team configuration file "zowe.config.json"
[2022/06/09 18:54:24.176] [DEBUG] [extension.js:32] Summary of team configuration files considered for Zowe Explorer: ["Path: C:\\Trv\\DepotsGIT\\environn-techleads-sandbox\\zowe.config.user.json: Not available ","Path: C:\\Trv\\DepotsGIT\\environn-techleads-sandbox\\zowe.config.json: Not available ","Path: C:\\Users\\S0070188\\.zowe\\zowe.config.user.json: Found, with the following defaults:{} ","Path: C:\\Users\\S0070188\\.zowe\\zowe.config.json: Found, with the following defaults:{\"ssh\":\"GMVS-SSH\",\"tso\":\"GMVS-TSO\",\"zftp\":\"GMVS-FTP\",\"zosmf\":\"GMVS\"} "]
[2022/06/09 18:54:25.729] [DEBUG] [extension.js:32] Initializing profiles with data set favorites.
[2022/06/09 18:54:25.733] [DEBUG] [extension.js:32] No data set favorites found.
[2022/06/09 18:54:30.299] [DEBUG] [extension.js:32] Initializing profiles with USS favorites.
[2022/06/09 18:54:30.312] [DEBUG] [extension.js:32] No USS favorites found.
[2022/06/09 18:54:34.024] [DEBUG] [extension.js:32] Initializing profiles with jobs favorites.
[2022/06/09 18:54:41.381] [DEBUG] [extension.js:32] [r [Error]: An error occurred collecting all configurations from the profile root directory "C:\Users\S0070188\.zowe\profiles". Please supply the configurations on the profile manager constructor parameters OR initialize the profile manager environment. Details: Profile IO Error: A Zowe V1 profile operation was attempted with a Zowe V2 configuration in use.
	at new d (c:\Users\S0070188\.vscode\extensions\zowe.vscode-extension-for-zowe-2.0.3\out\src\extension.js:72:269457)
	at new c (c:\Users\S0070188\.vscode\extensions\zowe.vscode-extension-for-zowe-2.0.3\out\src\extension.js:72:261507)
	at new f (c:\Users\S0070188\.vscode\extensions\zowe.vscode-extension-for-zowe-2.0.3\out\src\extension.js:72:80679)
	at y.getCliProfileManager (c:\Users\S0070188\.vscode\extensions\zowe.vscode-extension-for-zowe-2.0.3\out\src\extension.js:52:68839)
	at y.getSchema (c:\Users\S0070188\.vscode\extensions\zowe.vscode-extension-for-zowe-2.0.3\out\src\extension.js:52:67470)
	at Function.getZoweVersion (c:\Users\S0070188\.vscode\extensions\ibm.zopeneditor-2.0.3\dist\extension.js:5:1121587)
	at Function.<anonymous> (c:\Users\S0070188\.vscode\extensions\ibm.zopeneditor-2.0.3\dist\extension.js:5:1020213)
	at Generator.next (<anonymous>)
	at s (c:\Users\S0070188\.vscode\extensions\ibm.zopeneditor-2.0.3\dist\extension.js:5:1014409)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)] {
  mDetails: {
    msg: 'An error occurred collecting all configurations from the profile root directory "C:\\Users\\S0070188\\.zowe\\profiles". Please supply the configurations on the profile manager constructor parameters OR initialize the profile manager environment. Details: Profile IO Error: A Zowe V1 profile operation was attempted with a Zowe V2 configuration in use.',
    additionalDetails: [r [Error]: Profile IO Error: A Zowe V1 profile operation was attempted with a Zowe V2 configuration in use.
    	at Function.crashInTeamConfigMode (c:\Users\S0070188\.vscode\extensions\zowe.vscode-extension-for-zowe-2.0.3\out\src\extension.js:72:97792)
    	at Function.getAllProfileDirectories (c:\Users\S0070188\.vscode\extensions\zowe.vscode-extension-for-zowe-2.0.3\out\src\extension.js:72:96536)
    	at f.collectAllConfigurations (c:\Users\S0070188\.vscode\extensions\zowe.vscode-extension-for-zowe-2.0.3\out\src\extension.js:72:286781)
    	at new d (c:\Users\S0070188\.vscode\extensions\zowe.vscode-extension-for-zowe-2.0.3\out\src\extension.js:72:269211)
    	at new c (c:\Users\S0070188\.vscode\extensions\zowe.vscode-extension-for-zowe-2.0.3\out\src\extension.js:72:261507)
    	at new f (c:\Users\S0070188\.vscode\extensions\zowe.vscode-extension-for-zowe-2.0.3\out\src\extension.js:72:80679)
    	at y.getCliProfileManager (c:\Users\S0070188\.vscode\extensions\zowe.vscode-extension-for-zowe-2.0.3\out\src\extension.js:52:68839)
    	at y.getSchema (c:\Users\S0070188\.vscode\extensions\zowe.vscode-extension-for-zowe-2.0.3\out\src\extension.js:52:67470)
    	at Function.getZoweVersion (c:\Users\S0070188\.vscode\extensions\ibm.zopeneditor-2.0.3\dist\extension.js:5:1121587)
    	at Function.<anonymous> (c:\Users\S0070188\.vscode\extensions\ibm.zopeneditor-2.0.3\dist\extension.js:5:1020213)
    	at Generator.next (<anonymous>)
    	at s (c:\Users\S0070188\.vscode\extensions\ibm.zopeneditor-2.0.3\dist\extension.js:5:1014409)
    	at processTicksAndRejections (node:internal/process/task_queues:96:5)] {
      mDetails: [Object],
      mMessage: 'Profile IO Error: A Zowe V1 profile operation was attempted with a Zowe V2 configuration in use.'
    }
  },
  mMessage: 'An error occurred collecting all configurations from the profile root directory "C:\\Users\\S0070188\\.zowe\\profiles". Please supply the configurations on the profile manager constructor parameters OR initialize the profile manager environment. Details: Profile IO Error: A Zowe V1 profile operation was attempted with a Zowe V2 configuration in use.'
}
[2022/06/09 18:54:42.460] [DEBUG] [extension.js:32] File was saved -- determining whether the file is a USS file or Data set.
 Comparing (case insensitive) c:\Users\S0070188\AppData\Roaming\Code\User\settings.json against directory C:\Trv\DepotsGIT\Temp\temp\_D_andC:\Trv\DepotsGIT\Temp\temp\_U_
[2022/06/09 18:54:42.465] [DEBUG] [extension.js:32] File c:\Users\S0070188\AppData\Roaming\Code\User\settings.json is not a data set or USS file 
```

**Comment by JTonda** [comment]
May be related to #1851
