### ISSUE TITLE
Unable to activate the extender extension in case of errors blocking Zowe Explorer from being activated

### ISSUE THREAD

**Issue by nickImbirev** [zowe/vscode-extension-for-zowe#1908]
**Describe the bug**

Currently, if there is an extension depending on the Zowe Explorer API, it is completely blocked from usage, if Zowe Explorer was not activated completely. In particular, it is unable to use the extender extension in case there is something wrong with profiles from the **other** extension. **The most important thing for us would be to have at least an understandable notification about the issue.**

This is what the user can only see in the Extension Host Output panel:
```
[exthost] [error] Activating extension Zowe.vscode-extension-for-zowe failed due to an error:
[2022-08-15 11:20:16.023] [exthost] [error] Error: Internal error: Tried to call a non-existing MVS API in API register: base
    at a.getMvsApi (c:\Users\sk648074\.vscode\extensions\zowe.vscode-extension-for-zowe-2.2.1\out\src\extension.js:13:75266)
    at Function.getMvsApi (c:\Users\sk648074\.vscode\extensions\zowe.vscode-extension-for-zowe-2.2.1\out\src\extension.js:13:73638)
    at A.<anonymous> (c:\Users\sk648074\.vscode\extensions\zowe.vscode-extension-for-zowe-2.2.1\out\src\extension.js:269:334491)
    at Generator.next (<anonymous>)
    at c:\Users\sk648074\.vscode\extensions\zowe.vscode-extension-for-zowe-2.2.1\out\src\extension.js:269:316318
    at new Promise (<anonymous>)
    at r (c:\Users\sk648074\.vscode\extensions\zowe.vscode-extension-for-zowe-2.2.1\out\src\extension.js:269:316063)
    at A.addSingleSession (c:\Users\sk648074\.vscode\extensions\zowe.vscode-extension-for-zowe-2.2.1\out\src\extension.js:269:334345)
    at A.<anonymous> (c:\Users\sk648074\.vscode\extensions\zowe.vscode-extension-for-zowe-2.2.1\out\src\extension.js:269:322473)
    at Generator.next (<anonymous>)
    at s (c:\Users\sk648074\.vscode\extensions\zowe.vscode-extension-for-zowe-2.2.1\out\src\extension.js:269:316120)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Expected behavior**

I would expect to have an ability at least to see the proper notification about the Zowe Extension activation issue or to be able to activate the extender extension, if there is no issue related to the Zowe Explorer API that the extension is going to use.

**Desktop (please complete the following information):**

- OS: MacOs
- Zowe Explorer Version: 2.2.1

**Comment by roman-kupriyanov** [comment]
Hi @zFernand0,

I retested this issue on multiple cases using v1-v2 profiles and can say that it looks better with the appearing pop-up message now. I am still not sure that all possible scenarios will produce the same result, but I could not think of some other ways to reproduce more of activation errors. Mostly those are incorrect Team config formats or wrong names for the v1 profiles.

![image](https://user-images.githubusercontent.com/91762867/221534259-5a11f1a9-ad74-4296-b9c7-9b3d74701621.png)

It is nice that the users now can see the notification about that something went wrong and quickly navigate to the Team config to possibly fix the issue. Thanks for adding this!

I have some other observations though:

1. The error details are still dropped into the Debug Console, which is not a very common place for the users to look for the logs. Would it be possible to report them in Output into the ZE channel? Probably the notification may include an extra "Show logs" button to quickly navigate to the Output panel.
2. If there is a problem of reading the v1 profile file (incorrect name or absent `_meta.yaml` file), it does show the error notification but "Show Config" does nothing and there is no indication what the problem is. This might be another reason to have a quick access to some error info too, described in 1.

Those are merely nice-to-have's, so feel free to close this issue if you think this is unachievable or a matter for other discussion.

**Comment by JillieBeanSim** [comment]
@rudyflores do you think this is complete with the final work that was done on next branch with activation?

**Comment by rudyflores** [comment]
I believe you mean this PR? https://github.com/zowe/vscode-extension-for-zowe/pull/2611 

I think this should be resolved, but why Zowe Explorer introduced this issue if to begin with Zowe Explorer originally activated everything in the background vs now it only activates the non-UI components in the background and then load the UI components when entering Zowe Explorer for the first time.
