### ISSUE TITLE
Profile Inactive Error (2)

### ISSUE THREAD

**Issue by zFernand0** [zowe/vscode-extension-for-zowe#2398]
Hi Team,

I am facing same issue, i created new connection of http://ip:port, but it still gives me same error that its an HTTP(S) connection.
Could someone please let me know the solution to fix it ?

Do i need some JAva updates for it, or some CLI ?

I am using VS Code --> Zowe Explorer
:
![image](https://github.com/zowe/vscode-extension-for-zowe/assets/98732548/4fd286dc-7870-42b0-bc35-40eb18dc5d43)

errorDetails: [i [Error]: z/OSMF REST API Error:
  http(s) request error event called
  Error: write EPROTO 12081672:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:..\..\third_party\boringssl\src\ssl\tls_record.cc:231:
  
  	at o.populateError (c:\Users\Krishan.Singh\.vscode\extensions\zowe.vscode-extension-for-zowe-2.9.1\out\src\extension.js:80:20446)
  	at ClientRequest.<anonymous> (c:\Users\Krishan.Singh\.vscode\extensions\zowe.vscode-extension-for-zowe-2.9.1\out\src\extension.js:80:12433)
  	at ClientRequest.emit (node:events:525:35)
  	at TLSSocket.socketErrorListener (node:_http_client:481:9)
  	at TLSSocket.emit (node:events:513:28)
  	at emitErrorNT (node:internal/streams/destroy:157:8)
  	at emitErrorCloseNT (node:internal/streams/destroy:122:3)
  	at process.processTicksAndRejections (node:internal/process/task_queues:83:21)] {
    mDetails: {
      msg: 'z/OSMF REST API Error:\n' +
        'http(s) request error event called\n' +
        'Error: write EPROTO 12081672:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:..\\..\\third_party\\boringssl\\src\\ssl\\tls_record.cc:231:\n',
      causeErrors: [Error: write EPROTO 12081672:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:..\..\third_party\boringssl\src\ssl\tls_record.cc:231:
      
      	at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)] {
        errno: -4046,
        code: 'EPROTO',
        syscall: 'write'
      },
      source: 'client',
      errorCode: undefined,
      **protocol: 'https',**
      port: 23,
      host: '999.999.99.99',
      basePath: '',
      httpStatus: undefined,
      errno: undefined,
      syscall: undefined,

_Originally posted by @Krishan0031 in https://github.com/zowe/vscode-extension-for-zowe/issues/1096#issuecomment-1651665631_

**Comment by JillieBeanSim** [comment]
Hey @zFernand0 error looks similar to issue I open in cli a while back
https://github.com/zowe/zowe-cli/issues/1329

**Comment by zFernand0** [comment]
I believe this might be due to the SDKs forcing `https` by default if no protocol is specified in the profile.
We may need to do some testing around this though 😋

**Comment by JillieBeanSim** [comment]
It would be nice to see the cli issue fixed as we still see it even when protocol for plugin's profile type is set to http, like it forces https regardless of setting 😺

**Comment by Madhubalan-p** [comment]
I am facing same issue. zowe explorer, ibm z openeditor are using https by default which creates a problem for we who have setup a zdt machine and trying out the rseapi. any suggestion to workaround this?
