### ISSUE TITLE
Zowe CLI Profile not found

### ISSUE THREAD

**Issue by Felix-Braun** [zowe/vscode-extension-for-zowe#2441]
**Describe the bug**

With the new Zowe Explorer version v2.10.0, on some Coworkers Workstations, VSCode can't find any Zowe Cli Profiles. If you try to create a new Team Configuration File, it creates a new Global Configuration file, but it does not find the Profiles which were defined in the Configuration file.
I cannot find the Issue, because on my Workstation it works fine.

**To Reproduce**

**Screenshots**

![image](https://github.com/zowe/vscode-extension-for-zowe/assets/125555172/9df63fad-fb44-494a-861c-32f0e8d1f906)

**Desktop (please complete the following information):**

OS: Windows 10 Enterprise
Zowe Explorer Version: v2.10.0
(Optional) Zowe CLI Version: v7.16.4
(Optional) Are you using Secure Credential Store? Yes

**Additional context**

**Comment by Felix-Braun** [comment]
Some log lines from Imperative.log:
`2023/09/04 09:05:49.692] [INFO] [DefaultCredentialManager.js:171] Successfully loaded secure value for service = 'Zowe' account = 'secure_config_props'`
`2023/09/04 09:05:49.696] [WARN] [OverridesLoader.js:134] Secure vault not enabled. Reason: Line 1: Unexpected token ILLEGAL`
Some log lines from zowe.log:
`[2023/09/04 09:32:29.946] [INFO] [extension.js:32] Initialized logger for Zowe Explorer
[2023/09/04 09:37:56.907] [ERROR] [extension.js:32] [ProfInfoErr: Failed to initialize secure credential manager
	at O.<anonymous> (c:\Users\ris0062\.vscode\extensions\zowe.vscode-extension-for-zowe-2.10.0\out\src\extension.js:271:31159)
	at Generator.throw (<anonymous>)
	at a (c:\Users\ris0062\.vscode\extensions\zowe.vscode-extension-for-zowe-2.10.0\out\src\extension.js:271:18906)] {
  mDetails: {
    errorCode: 'LoadCredMgrFailed',
    msg: 'Failed to initialize secure credential manager',
    causeErrors: [Error: Line 1: Unexpected token ILLEGAL
    	at e.constructError (c:\Users\ris0062\.vscode\extensions\zowe.vscode-extension-for-zowe-2.10.0\out\src\extension.js:216:165259)
    	at e.createError (c:\Users\ris0062\.vscode\extensions\zowe.vscode-extension-for-zowe-2.10.0\out\src\extension.js:216:165478)
    	at e.throwError (c:\Users\ris0062\.vscode\extensions\zowe.vscode-extension-for-zowe-2.10.0\out\src\extension.js:216:165601)
    	at e.throwUnexpectedToken (c:\Users\ris0062\.vscode\extensions\zowe.vscode-extension-for-zowe-2.10.0\out\src\extension.js:216:170267)
    	at e.scanPunctuator (c:\Users\ris0062\.vscode\extensions\zowe.vscode-extension-for-zowe-2.10.0\out\src\extension.js:216:177839)
    	at e.lex (c:\Users\ris0062\.vscode\extensions\zowe.vscode-extension-for-zowe-2.10.0\out\src\extension.js:216:186357)
    	at e.getNextToken (c:\Users\ris0062\.vscode\extensions\zowe.vscode-extension-for-zowe-2.10.0\out\src\extension.js:216:191577)
    	at t.tokenize (c:\Users\ris0062\.vscode\extensions\zowe.vscode-extension-for-zowe-2.10.0\out\src\extension.js:216:58634)
    	at w (c:\Users\ris0062\.vscode\extensions\zowe.vscode-extension-for-zowe-2.10.0\out\src\extension.js:216:55595)
    	at Object.parse (c:\Users\ris0062\.vscode\extensions\zowe.vscode-extension-for-zowe-2.10.0\out\src\extension.js:216:57234)
    	at u.<anonymous> (c:\Users\ris0062\.vscode\extensions\zowe.vscode-extension-for-zowe-2.10.0\out\src\extension.js:241:15311)
    	at Generator.next (<anonymous>)
    	at s (c:\Users\ris0062\.vscode\extensions\zowe.vscode-extension-for-zowe-2.10.0\out\src\extension.js:241:14721)] {
      index: 1,
      lineNumber: 1,
      description: 'Unexpected token ILLEGAL'
    }
  },
  mMessage: 'Failed to initialize secure credential manager',
  mItemsInError: []
}`

**Comment by t1m0thyj** [comment]
Thanks for providing the logs. Based on the "Unexpected token ILLEGAL" error, I believe that Zowe Explorer is failing to parse secure values stored in the Windows credential vault.

On the workstation where Zowe Explorer is failing to load profiles, could you try these steps?
1. Open Credential Manager and navigate to the "Windows Credentials" section. See [here](https://support.microsoft.com/en-us/windows/accessing-credential-manager-1b5c916a-6a16-889f-8581-fc16e8165ac0) for how to access it - it should look similar to the image below.
2. Scroll down in the list of credentials and look for items whose name starts with `Zowe/secure_config_props`. You may have just one, or there may be multiple items suffixed with "-1", "-2", etc as shown in the image below.
3. Click the "down arrow" icon to expand these "Zowe" items and then click the "Remove" button for each one.
    **Warning:** This will reset any saved credentials and you'll have to enter them again when prompted in Zowe Explorer.
4. After removing the "Zowe" credentials, try to use Zowe Explorer again and let us know if the problem persists.

<p align="center">
  <img src="https://github.com/zowe/vscode-extension-for-zowe/assets/22344007/f3f2da59-6703-4369-9f49-c36d7726ce44">
</p>

**Comment by Felix-Braun** [comment]
Thank you, that fixed the problem
