### ISSUE TITLE
Zowe Explorer REST API error

### ISSUE THREAD

**Issue by juler69** [zowe/vscode-extension-for-zowe#739]
When I try to retrieve a list of datasets I get the following error:
Retrieving response from zowe.List Error: z/OSMF REST API Error: http(s) request error event called Error: Client network socket disconnected before secure TLS connection was established

I don't get this error when using Zowe CLI, I get the expected list of datasets.

I get the same error no matter what I try in Zowe Explorer.  I can't find anything useful in any logs either it seems.

I am using the latest version of Zowe Explorer and Zowe CLI.  I have the secure credential provider plugin.  It wasn't working even before I installed that though.

**Comment by jellypuno** [comment]
Have you set-up the Secure Credential in Zowe Explorer? https://github.com/zowe/vscode-extension-for-zowe/blob/master/docs/README-Security.md

Also, Just to be sure, do you have NodeJS 8 or higher?

**Comment by juler69** [comment]
> Have you set-up the Secure Credential in Zowe Explorer? https://github.com/zowe/vscode-extension-for-zowe/blob/master/docs/README-Security.md
> 
> Also, Just to be sure, do you have NodeJS 8 or higher?

Hi there, 

Thanks for the quick reply.

Yes I have set up according to those instructions.  Note though it didn't work even before I added this plugin so it is unlikely to be the cause per se, no?

I have:
NodeJS 12.16.2
npm 6.14.4
zowe cli 6.12.0

When I run zowe --version I get the following:
(base) C02Y86C9JG5H:~ xxxxxxx$ zowe --version
[2020/04/28 17:04:61] [ERROR] [CredentialManagerFactory.js:147] Failed to override the credential manager with one provided by "Zowe Explorer"
[2020/04/28 17:04:62] [ERROR] [CredentialManagerFactory.js:149] You attempted to override the "CredentialManager" setting with a plugin named "Zowe Explorer" that is not installed and loadable.
We will use a "CredentialManager" that purposely fails until you reconfigure.
6.12.0

Kind regards,

Jonathan

**Comment by juler69** [comment]
Clicked the wrong button...oops.

Here is the Zowe log from the vscode extension folders:

[2020/04/28 18:32:18.885] [DEBUG] [extension.js:165] File was saved -- determining whether the file is a USS file or Data set.
 Comparing (case insensitive) /Users/XXXXXXX/.vscode/extensions/zowe.vscode-extension-for-zowe-1.4.1/logs/zowe.log against directory /Users/XXXXXXX/.vscode/extensions/zowe.vscode-extension-for-zowe-1.4.1/resources/temp/_D_and/Users/XXXXXXX/.vscode/extensions/zowe.vscode-extension-for-zowe-1.4.1/resources/temp/_U_
[2020/04/28 18:32:18.887] [DEBUG] [extension.js:178] File /Users/XXXXXXX/.vscode/extensions/zowe.vscode-extension-for-zowe-1.4.1/logs/zowe.log is not a data set or USS file 
[2020/04/28 18:32:26.901] [DEBUG] [DatasetTree.js:525] Prompting the user for a data set pattern
[2020/04/28 18:32:31.546] [DEBUG] [ZosmfSession.js:26] Creating a z/OSMF session from the profile named %s
[2020/04/28 18:32:31.547] [DEBUG] [List.js:123] Endpoint: /zosmf/restfiles/ds?dslevel=XXXXXXX
[2020/04/28 18:32:31.589] [DEBUG] [extension.js:165] File was saved -- determining whether the file is a USS file or Data set.
 Comparing (case insensitive) /Users/XXXXXXX/Library/Application Support/Code/User/settings.json against directory /Users/XXXXXXX/.vscode/extensions/zowe.vscode-extension-for-zowe-1.4.1/resources/temp/_D_and/Users/XXXXXXX/.vscode/extensions/zowe.vscode-extension-for-zowe-1.4.1/resources/temp/_U_
[2020/04/28 18:32:31.590] [DEBUG] [extension.js:178] File /Users/XXXXXXX/Library/Application Support/Code/User/settings.json is not a data set or USS file 
[2020/04/28 18:32:41.722] [DEBUG] [ZosmfRestClient.js:70] Encountered an error trying to parse causeErrors as JSON  - causeErrors is likely not JSON format
[2020/04/28 18:32:41.722] [DEBUG] [AbstractRestClient.js:493] Error was processed by overridden processError method in RestClient ZosmfRestClient
[2020/04/28 18:32:41.723] [ERROR] [List.js:132] [RestClientError: z/OSMF REST API Error:
http(s) request error event called
Error: Client network socket disconnected before secure TLS connection was established
	at ZosmfRestClient.populateError (/Users/XXXXXXX/.vscode/extensions/zowe.vscode-extension-for-zowe-1.4.1/node_modules/@zowe/imperative/lib/rest/src/client/AbstractRestClient.js:497:16)
	at ClientRequest.<anonymous> (/Users/XXXXXXX/.vscode/extensions/zowe.vscode-extension-for-zowe-1.4.1/node_modules/@zowe/imperative/lib/rest/src/client/AbstractRestClient.js:124:29)
	at ClientRequest.emit (events.js:203:13)
	at TLSSocket.socketErrorListener (_http_client.js:399:9)
	at TLSSocket.emit (events.js:203:13)
	at emitErrorNT (internal/streams/destroy.js:91:8)
	at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
	at processTicksAndRejections (internal/process/task_queues.js:77:11)] {
  mDetails: {
    msg: 'z/OSMF REST API Error:\n' +
      'http(s) request error event called\n' +
      'Error: Client network socket disconnected before secure TLS connection was established',
    causeErrors: [Error: Client network socket disconnected before secure TLS connection was established
    	at connResetException (internal/errors.js:559:14)
    	at TLSSocket.onConnectEnd (_tls_wrap.js:1357:19)
    	at Object.onceWrapper (events.js:291:20)
    	at TLSSocket.emit (events.js:208:15)
    	at endReadableNT (_stream_readable.js:1168:12)
    	at processTicksAndRejections (internal/process/task_queues.js:77:11)] {
      code: 'ECONNRESET',
      path: undefined,
      host: null,
      port: null,
      localAddress: undefined
    },
    source: 'client',
    errorCode: undefined,
    port: 1111,
    host: '<redacted>',
    basePath: '',
    httpStatus: undefined,
    errno: undefined,
    syscall: undefined,
    payload: undefined,
    headers: [ [Object], [Object], [Object] ],
    resource: '/zosmf/restfiles/ds?dslevel=XXXXXXX',
    request: 'GET',
    additionalDetails: 'HTTP(S) client encountered an error. Request could not be initiated to host.\n' +
      'Review connection details (host, port) and ensure correctness.\n' +
      '\n' +
      'Host:      <redacted>\n' +
      'Port:      1111\n' +
      'Base Path: \n' +
      'Resource:  /zosmf/restfiles/ds?dslevel=XXXXXXX\n' +
      'Request:   GET\n' +
      'Headers:   [{"X-IBM-Attributes":"base"},{"X-IBM-Max-Items":"0"},{"X-CSRF-ZOSMF-HEADER":true}]\n' +
      'Payload:   undefined'
  },
  mMessage: 'z/OSMF REST API Error:\n' +
    'http(s) request error event called\n' +
    'Error: Client network socket disconnected before secure TLS connection was established'
}

Note the issue with the json file.  There's nothing wrong with this file as far as I can see.
I wrote a python script to read it and it didn't complain.

**Comment by jellypuno** [comment]
Thank you for posting the logs. I'm hoping that you just removed the information here and you don't have null as host and port?

So, one last thing, can you try to run `zowe scs u`?. if this doesn't help then I will need to analyze these logs.

**Comment by juler69** [comment]
The only thing I removed from the log was my username (replaced with XXXXXXX) and the hostname replaced with <redacted>.  Everything else is genuine log.

I guess the nulls are bad ;-)

**Comment by jellypuno** [comment]
@juler69 Is this still an open issue for you? I believe the TLS Connection Error is an issue in your network and not specific for Zowe Explorer. Can we close this issue?

**Comment by juler69** [comment]
I don't get this issue anymore - instead I get the **Profile <name> is inactive** error - which you raised a ticket about recently.  I commented on that ticket also.  Feel free to close this one.

**Comment by crawr** [comment]
Fix is available in v1.12.1

**Comment by Kshitija0110** [comment]
I want to copy the ZIGI files ZIGI.EXEC and ZIGI.PANELS but I'm getting this error.I've ensured that I'm giving correct credentials.
Please help.

/tmp/zigi-install/zigi > zowe zos-files upload dir-to-pds ZIGI.EXEC "ZXXXX.EXEC"
Enter the host name of your service: 204.90.115.200
Enter the user name for your service (will be hidden):
Enter the password for your service (will be hidden):
Command Error:
z/OSMF REST API Error:
http(s) request error event called
Error: connect ECONNREFUSED 204.90.115.200:443
Error Details:
HTTP(S) client encountered an error. Request could not be initiated to host.
Review connection details (host, port) and ensure correctness.

Protocol:  https
Host:      204.90.115.200
Port:      443
Base Path:
Resource:  /zosmf/restfiles/ds?dslevel=Z55188.EXEC&start=Z55188.EXEC
Request:   GET
Headers:   [{"Accept-Encoding":"gzip"},{"X-IBM-Attributes":"base"},{"X-IBM-Max-Items":"1"},{"X-IBM-Migrated-Recall":"wait"},{"X-CSRF-ZOSMF-HEADER":true}]      
Payload:   undefined

**Comment by zFernand0** [comment]
Hey @Kshitija0110, 
it seems that this is better suited for a question/discussion on the Zowe CLI repository.
- See: https://github.com/zowe/zowe-cli/issues/2408
